Repository uStudioTeam/brix-ui, pull requests merged in 2020-03, with the labels that each got.

#5 feat: Add StyledComponents decorator for Styled object
  packages/ui/src/utils/styles/styled-component.js
Labels: enhancement

#1 feat(Grid): Complete Grid API and behaviour
  packages/ui-website/components/ComponentInfo.tsx
  packages/ui-website/components/ComponentInfoItem.tsx
  packages/ui-website/components/PropsTable/PropsTable.tsx
  packages/ui-website/pages/components/drawer.tsx
  packages/ui-website/pages/components/grid.tsx
  packages/ui-website/pages/components/multiple-select.tsx
  packages/ui-website/pages/components/single-select.tsx
  packages/ui-website/pages/components/text.tsx
  packages/ui-website/pages/index.tsx
  packages/ui/src/components/Grid/Cell/index.d.ts
  packages/ui/src/components/Grid/Cell/index.jsx
  packages/ui/src/components/Grid/Grid/index.d.ts
  packages/ui/src/components/Grid/Grid/index.jsx
  packages/ui/src/components/Grid/stories/index.stories.jsx
  packages/ui/src/components/Grid/styled.js
  packages/ui/src/components/Grid/styles/index.js
  packages/ui/src/components/Grid/styles/inject.js
  packages/ui/src/components/Grid/types.d.ts
  packages/ui/src/components/Grid/utils/context.js
  packages/ui/src/components/Grid/utils/get-cell-template.js
  packages/ui/src/components/Grid/utils/get-grid-template.js
  packages/ui/src/components/Grid/utils/index.js
  packages/ui/src/theme/global-style.js
  packages/ui/src/theme/mixin/screen.js
  yarn.lock
Labels: documentation, enhancement

#12 refactor(Meta): Refactor Meta component
  packages/ui-website/pages/components/meta.tsx
  packages/ui/src/components/Meta/index.d.ts
  packages/ui/src/components/Meta/index.jsx
  packages/ui/src/components/Meta/stories/index.stories.jsx
  packages/ui/src/components/Meta/styled.js
  packages/ui/src/components/Meta/styles/index.js
  packages/ui/src/components/Meta/styles/inject.js
Labels: documentation, refactor

#17 refactor(Tooltip): Refactor Tooltip component
  packages/ui/src/components/Tooltip/index.jsx
  packages/ui/src/components/Tooltip/styled.js
  packages/ui/src/components/Tooltip/styles/index.js
  packages/ui/src/components/Tooltip/styles/inject.js
Labels: refactor

#18 refactor(Button): Refactor Button component
  packages/ui/src/components/Button/index.jsx
  packages/ui/src/components/Button/styles/index.js
  packages/ui/src/components/Button/styles/inject.js
  packages/ui/src/components/Input/styled.js
Labels: refactor

#19 refactor(Select): Refactor Select and MultiSelect components
  packages/ui/src/components/Select/BaseSelect/index.jsx
  packages/ui/src/components/Select/MultiSelect/index.jsx
  packages/ui/src/components/Select/Select/index.jsx
  packages/ui/src/components/Select/styled.js
  packages/ui/src/components/Select/styles/index.js
  packages/ui/src/components/Select/styles/inject.js
  packages/ui/src/components/Select/utils/get-items-array.js
  packages/ui/src/components/Select/utils/get-items-map.js
  packages/ui/src/components/Select/utils/index.js
Labels: refactor

#20 refactor(Checkbox): Refactor Checkbox component
  packages/ui/src/components/Checkbox/index.jsx
  packages/ui/src/components/Checkbox/styles/index.js
  packages/ui/src/components/Checkbox/styles/inject.js
Labels: refactor

#21 refactor(Switch): Refactor Switch component
  packages/ui/src/components/Switch/index.jsx
  packages/ui/src/components/Switch/styles/index.js
  packages/ui/src/components/Switch/styles/inject.js
Labels: refactor

#22 refactor(RadioGroup): Refactor RadioGroup component
  packages/ui/src/components/RadioGroup/index.jsx
  packages/ui/src/components/RadioGroup/styles/index.js
  packages/ui/src/components/RadioGroup/styles/inject.js
Labels: refactor

#16 feat(EditableText): Refactor EditableText component
  packages/ui-website/pages/components/editable-text.tsx
  packages/ui/src/assets/icons/pen.svg
  packages/ui/src/components/EditableText/index.d.ts
  packages/ui/src/components/EditableText/index.jsx
  packages/ui/src/components/EditableText/stories/index.stories.jsx
  packages/ui/src/components/EditableText/styled.js
  packages/ui/src/components/EditableText/styles/index.js
  packages/ui/src/components/EditableText/styles/inject.js
  packages/ui/src/components/EditableText/utils/index.js
  packages/ui/src/components/Text/index.d.ts
  packages/ui/src/components/Text/index.jsx
  packages/ui/src/components/internal/Icon/index.jsx
Labels: documentation, feature, hotfix, refactor

#24 refactor(Progress): Refactor Progress component
  packages/ui/src/components/Progress/index.jsx
  packages/ui/src/components/Progress/styles/animation.js
  packages/ui/src/components/Progress/styles/index.js
  packages/ui/src/components/Progress/styles/inject.js
Labels: refactor

#28 refactor(Tabs): Refactor Tabs component
  packages/ui/src/components/Tabs/index.jsx
  packages/ui/src/components/Tabs/styles/index.js
  packages/ui/src/components/Tabs/styles/inject.js
Labels: refactor

#23 refactor(Spinner): Refactor Spinner component
  packages/ui/src/components/Spinner/index.jsx
  packages/ui/src/components/Spinner/styled.js
  packages/ui/src/components/Spinner/styles/animation.js
  packages/ui/src/components/Spinner/styles/index.js
  packages/ui/src/components/Spinner/styles/inject.js
Labels: refactor

#26 refactor(Input): Refactor TextInput, TextArea, NumberInput and FileInput components
  packages/ui-website/pages/components/file-input.tsx
  packages/ui-website/pages/components/number-input.tsx
  packages/ui-website/pages/components/text-area.tsx
  packages/ui-website/pages/components/text-input.tsx
  packages/ui/src/components/Input/BaseInput/index.jsx
  packages/ui/src/components/Input/FileInput/index.jsx
  packages/ui/src/components/Input/NumberInput/index.jsx
  packages/ui/src/components/Input/TextArea/index.jsx
  packages/ui/src/components/Input/TextInput/index.jsx
  packages/ui/src/components/Input/stories/index.stories.jsx
  packages/ui/src/components/Input/styles/index.js
  packages/ui/src/components/Input/styles/inject.js
Labels: refactor

#29 refactor(Slider): Refactor Slider component
  packages/ui-website/pages/components/slider.tsx
  packages/ui/src/components/Slider/index.jsx
  packages/ui/src/components/Slider/stories/index.stories.jsx
  packages/ui/src/components/Slider/styled.js
  packages/ui/src/components/Slider/styles/index.js
  packages/ui/src/components/Slider/styles/inject.js
  packages/ui/src/components/Slider/utils/index.js
Labels: refactor

#25 refactor(Placeholder): Refactor Placeholder component
  packages/ui/src/components/Placeholder/index.jsx
  packages/ui/src/components/Placeholder/styled.js
  packages/ui/src/components/Placeholder/styles/animation.js
  packages/ui/src/components/Placeholder/styles/index.js
  packages/ui/src/components/Placeholder/styles/inject.js
Labels: refactor

#73 Merge Grid breakpoint props
  packages/ui-website/pages/components/grid.tsx
Labels: documentation, enhancement

#72 fix: rename Container styled-components, fix classNames props
  packages/ui-website/pages/components/badge.tsx
  packages/ui-website/pages/components/checkbox.tsx
  packages/ui-website/pages/components/drawer.tsx
  packages/ui-website/pages/components/dropdown.tsx
  packages/ui-website/pages/components/editable-text.tsx
  packages/ui-website/pages/components/file-input.tsx
  packages/ui-website/pages/components/meta.tsx
  packages/ui-website/pages/components/modal.tsx
  packages/ui-website/pages/components/multiple-select.tsx
  packages/ui-website/pages/components/radio-group.tsx
  packages/ui-website/pages/components/single-select.tsx
  packages/ui-website/pages/components/slider.tsx
  packages/ui-website/pages/components/switch.tsx
  packages/ui-website/pages/components/tooltip.tsx
  packages/ui/src/components/Checkbox/index.jsx
  packages/ui/src/components/Checkbox/styles/index.js
  packages/ui/src/components/Input/FileInput/index.d.ts
  packages/ui/src/components/Input/FileInput/index.jsx
  packages/ui/src/components/RadioGroup/index.d.ts
  packages/ui/src/components/RadioGroup/styles/index.js
  packages/ui/src/components/Select/styles/index.js
  packages/ui/src/components/Select/types.d.ts
  packages/ui/src/components/Slider/index.d.ts
  packages/ui/src/components/Switch/index.d.ts
  packages/ui/src/components/Switch/index.jsx
  packages/ui/src/components/Switch/styles/index.js
  packages/ui/src/components/Tooltip/index.d.ts
  packages/ui/src/components/Tooltip/index.jsx
Labels: documentation, feature, refactor

#69 feat: Change inputs label prop to name and id props
  packages/ui-website/components/PropsTable/input-props.ts
  packages/ui-website/pages/components/checkbox.tsx
  packages/ui-website/pages/components/file-input.tsx
  packages/ui-website/pages/components/multiple-select.tsx
  packages/ui-website/pages/components/number-input.tsx
  packages/ui-website/pages/components/radio-group.tsx
  packages/ui-website/pages/components/single-select.tsx
  packages/ui-website/pages/components/slider.tsx
  packages/ui-website/pages/components/switch.tsx
  packages/ui-website/pages/components/text-area.tsx
  packages/ui-website/pages/components/text-input.tsx
  packages/ui/src/components/Checkbox/index.jsx
  packages/ui/src/components/Checkbox/stories/index.stories.jsx
  packages/ui/src/components/Dropdown/stories/index.stories.jsx
  packages/ui/src/components/EditableText/index.jsx
  packages/ui/src/components/Input/BaseInput/index.jsx
  packages/ui/src/components/Input/FileInput/index.jsx
  packages/ui/src/components/Input/NumberInput/index.jsx
  packages/ui/src/components/Input/TextArea/index.jsx
  packages/ui/src/components/Input/TextInput/index.jsx
  packages/ui/src/components/Input/stories/index.stories.jsx
  packages/ui/src/components/RadioGroup/index.jsx
  packages/ui/src/components/RadioGroup/stories/index.stories.jsx
  packages/ui/src/components/Select/BaseSelect/index.jsx
  packages/ui/src/components/Select/MultiSelect/index.jsx
  packages/ui/src/components/Select/Select/index.jsx
  packages/ui/src/components/Select/stories/index.stories.jsx
  packages/ui/src/components/Slider/index.jsx
  packages/ui/src/components/Slider/stories/index.stories.jsx
  packages/ui/src/components/Switch/index.jsx
  packages/ui/src/components/Switch/stories/index.stories.jsx
  packages/ui/src/input.d.ts
  packages/ui/src/utils/prop-types/input-props.js
Labels: documentation, feature, refactor

#74 feat(Meta, Website): Add target="_blank" to link in code example
  packages/ui-website/pages/components/meta.tsx
Labels: documentation, feature

#75 Add default values for style props
  packages/ui-website/pages/components/badge.tsx
  packages/ui-website/pages/components/placeholder.tsx
  packages/ui-website/pages/components/spinner.tsx
  packages/ui-website/pages/components/tag.tsx
  packages/ui/src/components/Badge/styles/inject.js
  packages/ui/src/components/Tag/styles/inject.js
Labels: documentation, feature

#77 fix(Button): Fix Button styles
  packages/ui/src/components/Button/index.jsx
  packages/ui/src/components/Button/styles/inject.js
Labels: hotfix, refactor

#78 fix(Dropdown): Fix PropTypes
  packages/ui-website/pages/components/dropdown.tsx
  packages/ui/src/components/Dropdown/index.d.ts
  packages/ui/src/components/Dropdown/index.jsx
Labels: documentation, hotfix

#79 fix(Tabs): Fix tab active cursor
  packages/ui/src/components/Tabs/styles/index.js
  packages/ui/src/components/Tabs/styles/inject.js
Labels: hotfix

#80 fix(Grid): Fix Grid and Cell children types
  packages/ui-website/pages/components/grid.tsx
  packages/ui/src/components/Grid/Cell/index.d.ts
  packages/ui/src/components/Grid/Grid/index.d.ts
  packages/ui/src/components/Grid/types.d.ts
Labels: documentation, hotfix

#81 fix(Flex, Website): Add default value for direction
  packages/ui-website/pages/components/flex.tsx
Labels: documentation, hotfix

#84 fix(Modal): Fix opening of modal
  packages/ui/src/components/Modal/styles/index.js
Labels: hotfix

#85 feat(Slider, Website): Decrease step size for slider example
  packages/ui-website/pages/components/slider.tsx
Labels: documentation, feature

#86 fix(Multiselect, Website): Made select example fullwidth
  packages/ui-website/pages/components/multiple-select.tsx
Labels: documentation, hotfix

#82 feat(RadioGroup): Change options API
  packages/ui-website/pages/components/radio-group.tsx
  packages/ui/src/components/RadioGroup/index.d.ts
  packages/ui/src/components/RadioGroup/index.jsx
  packages/ui/src/components/RadioGroup/stories/index.stories.jsx
  packages/ui/src/components/RadioGroup/utils/index.js
Labels: documentation, feature, refactor

#87 fix(TextArea): Add type extending from HTMLTextAreaElement
  packages/ui/src/components/Input/TextArea/index.d.ts
Labels: hotfix

#88 fix(EditableText, Website): Change value and onChange in props table
  packages/ui-website/pages/components/editable-text.tsx
  packages/ui/src/components/EditableText/index.jsx
Labels: documentation, hotfix

#89 feat(Select): Add placeholder prop
  packages/ui-website/pages/components/multiple-select.tsx
  packages/ui-website/pages/components/single-select.tsx
  packages/ui/src/components/Select/BaseSelect/index.jsx
  packages/ui/src/components/Select/MultiSelect/index.jsx
  packages/ui/src/components/Select/Select/index.jsx
  packages/ui/src/components/Select/stories/index.stories.jsx
  packages/ui/src/components/Select/styles/index.js
  packages/ui/src/components/Select/types.d.ts
Labels: documentation, feature, hotfix

#90 Add logo to README.md
  CONTRIBUTING.md
  README.md
  banner.jpg
  packages/ui-website/README.md
  packages/ui-website/pages/docs/installation.tsx
Labels: documentation, enhancement

#91 fix(Grid, Website) Update grid documentation
  packages/ui-website/pages/components/grid.tsx
Labels: documentation, hotfix

#92 fix(RadioGroup, Website): Fix disabled styles, update docs
  packages/ui-website/pages/components/radio-group.tsx
  packages/ui/src/components/RadioGroup/styles/index.js
Labels: documentation, hotfix

#93 Fix README.md
  README.md
Labels: documentation, hotfix

#76 fix(Text, Website): Change direction of examples container
  packages/ui-website/pages/components/text.tsx
Labels: documentation, hotfix

#95 fix(Select, MultipleSelect): Remove transition delay
  packages/ui/src/components/Select/styles/inject.js
Labels: hotfix

#96 fix(NumberInput): Number input validation
  packages/ui/src/components/Input/NumberInput/index.jsx
Labels: hotfix

#107 Fix: Fix npm-script
  packages/ustudio-ui/package.json
Labels: hotfix

#108 Fix: Fix npm-script
  packages/ustudio-ui/package.json
Labels: hotfix

#120 hotfix: Fix Grid children type validation and maxWidth calculation, add full-width to Flex
  packages/docs-website/package.json
  packages/ustudio-ui/package.json
  packages/ustudio-ui/src/components/Flex/styles/index.js
  packages/ustudio-ui/src/components/Grid/Grid/index.d.ts
  packages/ustudio-ui/src/components/Grid/Grid/index.jsx
  packages/ustudio-ui/src/components/Grid/index.d.ts
  packages/ustudio-ui/src/components/Grid/stories/index.stories.jsx
  packages/ustudio-ui/src/components/Grid/styles/inject.js
  packages/ustudio-ui/src/components/Grid/utils/index.js
Labels: feature, hotfix

#121 hotfix: Fix Grid children type validation and maxWidth calculation, add full-width to Flex
  packages/docs-website/package.json
  packages/ustudio-ui/package.json
  packages/ustudio-ui/src/components/Flex/styles/index.js
  packages/ustudio-ui/src/components/Grid/Grid/index.d.ts
  packages/ustudio-ui/src/components/Grid/Grid/index.jsx
  packages/ustudio-ui/src/components/Grid/index.d.ts
  packages/ustudio-ui/src/components/Grid/stories/index.stories.jsx
  packages/ustudio-ui/src/components/Grid/styles/inject.js
  packages/ustudio-ui/src/components/Grid/utils/index.js
Labels: feature, hotfix

#122 Fix(Website): Fix target blank for internal links
  packages/docs-website/components/markdown/renderers.tsx
Labels: documentation, hotfix

#125 Feat: Add to package.json keywords, homepage and repository
  packages/ustudio-ui/package.json
Labels: feature

#124 Feat(README): Add to readme sections with contributing and issues
  README.md
Labels: feature
